### ISSUE TITLE
Crash when analysing relatively large x86 binary

### ISSUE THREAD

**Issue by ccarpenter04** [CySHell/ClassyPP#5]
I'm not sure what triggered the error, however after a couple hours of analysis this error was thrown. Please let me know if there's any other information I can provide.

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/2475433/201169909-10b9a4e2-3371-4b8f-8db5-66b83dd2a549.png">

**Comment by ccarpenter04** [comment]
I downloaded the plugin and ran it locally because trying to run it through the plugin manager resulted in some very... undesirable behavior...

**Comment by CySHell** [comment]
Can you please get the latest commit on main branch (https://github.com/CySHell/ClassyPP/commit/dd0b17eced64a884b4a1cb72fb18c712f1c26a85), run the plugin and send the log_debug.txt file ?

**Comment by ccarpenter04** [comment]
So I've done just that, however the log file is over a gigabyte in size. How would you like me to send it to you?

**Comment by CySHell** [comment]
please compress it (since its a text file it should compress nicely) and upload to:
https://1drv.ms/u/s!AkXMoA4QfqQ7gYOhfD1NxCpGKvJggyA?e=4K2MZm

**Comment by ccarpenter04** [comment]
Uploaded, please let me know if you figure out the issue, it took multiple hours to run. @CySHell

**Comment by CySHell** [comment]
Fixed in version 1.5
